# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/BME688-ARTYS7-50-SPI-MAIN/BME688-ARTYS7-50-SPI-MAIN.srcs/sources_1/bd/BME688/ip/BME688_ilmb_v10_0/BME688_ilmb_v10_0.xci
# IP: The module: 'BME688_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/BME688-ARTYS7-50-SPI-MAIN/BME688-ARTYS7-50-SPI-MAIN.gen/sources_1/bd/BME688/ip/BME688_ilmb_v10_0/BME688_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BME688_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/BME688-ARTYS7-50-SPI-MAIN/BME688-ARTYS7-50-SPI-MAIN.srcs/sources_1/bd/BME688/ip/BME688_ilmb_v10_0/BME688_ilmb_v10_0.xci
# IP: The module: 'BME688_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/BME688-ARTYS7-50-SPI-MAIN/BME688-ARTYS7-50-SPI-MAIN.gen/sources_1/bd/BME688/ip/BME688_ilmb_v10_0/BME688_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BME688_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
