# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Arty-S7-50-Master.xdc

# Block Designs: bd/BME688/BME688.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688 || ORIG_REF_NAME==BME688} -quiet] -quiet

# IP: bd/BME688/ip/BME688_mig_7series_0_0/BME688_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_mig_7series_0_0 || ORIG_REF_NAME==BME688_mig_7series_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_xlconstant_0_0/BME688_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_xlconstant_0_0 || ORIG_REF_NAME==BME688_xlconstant_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_clk_wiz_0_0/BME688_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_clk_wiz_0_0 || ORIG_REF_NAME==BME688_clk_wiz_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_microblaze_0_0/BME688_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_microblaze_0_0 || ORIG_REF_NAME==BME688_microblaze_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_dlmb_v10_0/BME688_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_dlmb_v10_0 || ORIG_REF_NAME==BME688_dlmb_v10_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_ilmb_v10_0/BME688_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_ilmb_v10_0 || ORIG_REF_NAME==BME688_ilmb_v10_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_dlmb_bram_if_cntlr_0/BME688_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==BME688_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_ilmb_bram_if_cntlr_0/BME688_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==BME688_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_lmb_bram_0/BME688_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_lmb_bram_0 || ORIG_REF_NAME==BME688_lmb_bram_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_microblaze_0_axi_intc_0/BME688_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_microblaze_0_axi_intc_0 || ORIG_REF_NAME==BME688_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_microblaze_0_xlconcat_0/BME688_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_microblaze_0_xlconcat_0 || ORIG_REF_NAME==BME688_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_mdm_1_0/BME688_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_mdm_1_0 || ORIG_REF_NAME==BME688_mdm_1_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_rst_clk_wiz_0_100M_0/BME688_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==BME688_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_rst_mig_7series_0_81M_0/BME688_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==BME688_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_axi_uartlite_0_0/BME688_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_axi_uartlite_0_0 || ORIG_REF_NAME==BME688_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_axi_quad_spi_0_0/BME688_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_axi_quad_spi_0_0 || ORIG_REF_NAME==BME688_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_axi_quad_spi_1_0/BME688_axi_quad_spi_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_axi_quad_spi_1_0 || ORIG_REF_NAME==BME688_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_xbar_0/BME688_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_xbar_0 || ORIG_REF_NAME==BME688_xbar_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_microblaze_0_axi_periph_0/BME688_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_microblaze_0_axi_periph_0 || ORIG_REF_NAME==BME688_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_axi_gpio_0_1/BME688_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_axi_gpio_0_1 || ORIG_REF_NAME==BME688_axi_gpio_0_1} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_us_0/BME688_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_us_0 || ORIG_REF_NAME==BME688_auto_us_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_5/BME688_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_5 || ORIG_REF_NAME==BME688_auto_pc_5} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_us_1/BME688_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_us_1 || ORIG_REF_NAME==BME688_auto_us_1} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_us_2/BME688_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_us_2 || ORIG_REF_NAME==BME688_auto_us_2} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_ds_0/BME688_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_ds_0 || ORIG_REF_NAME==BME688_auto_ds_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_0/BME688_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_0 || ORIG_REF_NAME==BME688_auto_pc_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_cc_0/BME688_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_cc_0 || ORIG_REF_NAME==BME688_auto_cc_0} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_ds_1/BME688_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_ds_1 || ORIG_REF_NAME==BME688_auto_ds_1} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_1/BME688_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_1 || ORIG_REF_NAME==BME688_auto_pc_1} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_ds_2/BME688_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_ds_2 || ORIG_REF_NAME==BME688_auto_ds_2} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_2/BME688_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_2 || ORIG_REF_NAME==BME688_auto_pc_2} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_ds_3/BME688_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_ds_3 || ORIG_REF_NAME==BME688_auto_ds_3} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_3/BME688_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_3 || ORIG_REF_NAME==BME688_auto_pc_3} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_ds_4/BME688_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_ds_4 || ORIG_REF_NAME==BME688_auto_ds_4} -quiet] -quiet

# IP: bd/BME688/ip/BME688_auto_pc_4/BME688_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BME688_auto_pc_4 || ORIG_REF_NAME==BME688_auto_pc_4} -quiet] -quiet

# XDC: c:/Users/cloud/OneDrive/_Arty_Spartan_7/Projects/BME688-ARTYS7-50-SPI-MAIN/BME688-ARTYS7-50-SPI-MAIN.gen/sources_1/bd/BME688/BME688_ooc.xdc
