domain_path: C:\Users\cloud\OneDrive\_Arty_Spartan_7\Projects\BME688-ARTYS7-50-SPI-MAIN\BME688_plat\export\BME688_plat\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
